ALTER TABLE boarding     ADD COLUMN IF NOT EXISTS paid BOOLEAN DEFAULT FALSE;
ALTER TABLE cirugias     ADD COLUMN IF NOT EXISTS paid BOOLEAN DEFAULT FALSE;
ALTER TABLE pet_vaccines ADD COLUMN IF NOT EXISTS paid BOOLEAN DEFAULT FALSE;
